# Generated by Django 3.0 on 2020-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='explicit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
