# Generated by Django 3.0 on 2020-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_explicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
    ]
